## Homework Linear Algebra: Solving Equations

### Sahana Bhattacharyya
### Banner Id: 000139658


In [4]:
# Problem 6.7 Part:1 (N=0 .....1000 this program works)

import numpy as np
from numpy import zeros
N = int(input("No of vector elements "))
a = zeros([N,N], float)

V = zeros([N,1], float)
V[0,0] = V[1, 0] = 5

#print("Vector", V)

a[0,0] = a[N-1, N-1] = 3
a[0,1]=a[0,2]=a[1,2]=a[1,3]=a[1,0] =-1
a[1,1] = a[N-2, N-2] = 4

a[N-2, N-4] = a[N-2, N-3] = a[N-2, N-1] = a[N-1, N-3] = a[N-1, N-2] = -1


for i in range (2, N-2):
    j = i -2
    a[i, j] = -1                    #V[i-2]
    a[i, j+1] = -1                  #V[i-1]
    a[i, j+2] = 4                   #*V[i]
    a[i, j+3] = -1                  #V[i+1]
    a[i, j+4] = -1                  #V[i+2]

print(a)

#Gaussian elimination
for m in range(N):
    div = a[m,m]               #divide by the diagonal element
    a[m,:]/=div                #[m,:] means divide all the elements of the row 
    V[m]/=div
    
    #Subtract from the lower rows
    for i in range (m+1,N):
        mult = a[i,m]
        a[i,:]-= mult*a[m,:]
        V[i]-= mult*V[m]
        
print(a)

#Backsubstitution
x = zeros(N,float)
for m in range (N-1, -1, -1):
    x[m] = V[m]
    for i in range(m+1,N):
        x[m] -=a[m,i]*x[i]
print(x)

No of vector elements 6
[[ 3. -1. -1.  0.  0.  0.]
 [-1.  4. -1. -1.  0.  0.]
 [-1. -1.  4. -1. -1.  0.]
 [ 0. -1. -1.  4. -1. -1.]
 [ 0.  0. -1. -1.  4. -1.]
 [ 0.  0.  0. -1. -1.  3.]]
[[ 1.         -0.33333333 -0.33333333  0.          0.          0.        ]
 [ 0.          1.         -0.36363636 -0.27272727  0.          0.        ]
 [ 0.          0.          1.         -0.42857143 -0.31428571  0.        ]
 [ 0.          0.          0.          1.         -0.45454545 -0.31818182]
 [ 0.          0.          0.          0.          1.         -0.47904192]
 [ 0.          0.          0.          0.          0.          1.        ]]
[ 3.7254902   3.43137255  2.74509804  2.25490196  1.56862745  1.2745098 ]


In [6]:
from numpy import copy

import numpy as np
from numpy import zeros
N = int(input("No of vector elements "))
A = zeros([N,N], float)

V = zeros([N,1], float)
V[0,0] = V[1, 0] = 5

#print("Vector", V)

A[0,0] = A[N-1, N-1] = 3
A[0,1]=A[0,2]=A[1,2]=A[1,3]=A[1,0] =-1
A[1,1] = A[N-2, N-2] = 4

A[N-2, N-4] = A[N-2, N-3] = A[N-2, N-1] = A[N-1, N-3] = A[N-1, N-2] = -1


for i in range (2, N-2):
    j = i -2
    A[i, j] = -1                    #V[i-2]
    A[i, j+1] = -1                  #V[i-1]
    A[i, j+2] = 4                   #*V[i]
    A[i, j+3] = -1                  #V[i+1]
    A[i, j+4] = -1                  #V[i+2]

print(A)

def banded(Aa,va,up,down):
    A = copy(Aa)
    v = copy(va)
    N = len(v)
    
#Gaussian elimination 
for m in range (N):
    div = A[up,m]            #Normalisation factor
    v[m] /=div               #Update the vector first
    
    for k in range (1,down+1):
        if m+k<N:
            v[m+k] -=A[up+k,m]*v[m]
        
        # Now normalise and subtratct the pivot row
        for j in range(up):
            j = m+up-i
            if j<N:
                A[i,j] /= div
                for k in range(1,down+1):
                    A[i+k,j] -= A[up+k,m]*A[i,j]
                    
#Backsubstitution 
for m in range(N-2,-1,-1):
    for i in range(up):
        j = m +up -i
        if j<N:
            v[m] -= A[i,j]*v[j]

No of vector elements 6
[[ 3. -1. -1.  0.  0.  0.]
 [-1.  4. -1. -1.  0.  0.]
 [-1. -1.  4. -1. -1.  0.]
 [ 0. -1. -1.  4. -1. -1.]
 [ 0.  0. -1. -1.  4. -1.]
 [ 0.  0.  0. -1. -1.  3.]]


NameError: name 'up' is not defined